### ISSUE TITLE
Mark this as obsolete?

### ISSUE THREAD

**Issue by nlharris** [ModelSEED/KBaseClient#2]
I assume this won't work right anymore. Should we do something to indicate that this repo is obsolete?

**Comment by cshenry** [comment]
No, this is not obsolete and works perfectly well. Me and my group and many of our collaborators use it all the time. And it will continue to work indefinitely as far as I know. There are no plans to kill it.

**Comment by nlharris** [comment]
Ok, sorry! Thanks for the clarification! I wonder if we should be promoting it more, then?

**Comment by cshenry** [comment]
I wouldn't say that either. I think it's fine as is. It's a prototype, and there are things we should change before attempting to really build out a larger user-base for this. The Narrative is our primary product, and I worry that promoting this would be a distraction

**Comment by cshenry** [comment]
The long term goal, for example, would be to orient the CLI commands in this system towards an API presented by the narrative, so by using this CLI, you are working harmoniously with the narrative. If we achieve this, then I would move it to a "KBase" repo, and I would most definitely promote it.
